require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TransactionalsController do

  # This should return the minimal set of attributes required to create a valid
  # Transactional. As you add validations to Transactional, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "xml" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TransactionalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all transactionals as @transactionals" do
      transactional = Transactional.create! valid_attributes
      get :index, {}, valid_session
      assigns(:transactionals).should eq([transactional])
    end
  end

  describe "GET show" do
    it "assigns the requested transactional as @transactional" do
      transactional = Transactional.create! valid_attributes
      get :show, {:id => transactional.to_param}, valid_session
      assigns(:transactional).should eq(transactional)
    end
  end

  describe "GET new" do
    it "assigns a new transactional as @transactional" do
      get :new, {}, valid_session
      assigns(:transactional).should be_a_new(Transactional)
    end
  end

  describe "GET edit" do
    it "assigns the requested transactional as @transactional" do
      transactional = Transactional.create! valid_attributes
      get :edit, {:id => transactional.to_param}, valid_session
      assigns(:transactional).should eq(transactional)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Transactional" do
        expect {
          post :create, {:transactional => valid_attributes}, valid_session
        }.to change(Transactional, :count).by(1)
      end

      it "assigns a newly created transactional as @transactional" do
        post :create, {:transactional => valid_attributes}, valid_session
        assigns(:transactional).should be_a(Transactional)
        assigns(:transactional).should be_persisted
      end

      it "redirects to the created transactional" do
        post :create, {:transactional => valid_attributes}, valid_session
        response.should redirect_to(Transactional.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transactional as @transactional" do
        # Trigger the behavior that occurs when invalid params are submitted
        Transactional.any_instance.stub(:save).and_return(false)
        post :create, {:transactional => { "xml" => "invalid value" }}, valid_session
        assigns(:transactional).should be_a_new(Transactional)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Transactional.any_instance.stub(:save).and_return(false)
        post :create, {:transactional => { "xml" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transactional" do
        transactional = Transactional.create! valid_attributes
        # Assuming there are no other transactionals in the database, this
        # specifies that the Transactional created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Transactional.any_instance.should_receive(:update_attributes).with({ "xml" => "MyText" })
        put :update, {:id => transactional.to_param, :transactional => { "xml" => "MyText" }}, valid_session
      end

      it "assigns the requested transactional as @transactional" do
        transactional = Transactional.create! valid_attributes
        put :update, {:id => transactional.to_param, :transactional => valid_attributes}, valid_session
        assigns(:transactional).should eq(transactional)
      end

      it "redirects to the transactional" do
        transactional = Transactional.create! valid_attributes
        put :update, {:id => transactional.to_param, :transactional => valid_attributes}, valid_session
        response.should redirect_to(transactional)
      end
    end

    describe "with invalid params" do
      it "assigns the transactional as @transactional" do
        transactional = Transactional.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Transactional.any_instance.stub(:save).and_return(false)
        put :update, {:id => transactional.to_param, :transactional => { "xml" => "invalid value" }}, valid_session
        assigns(:transactional).should eq(transactional)
      end

      it "re-renders the 'edit' template" do
        transactional = Transactional.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Transactional.any_instance.stub(:save).and_return(false)
        put :update, {:id => transactional.to_param, :transactional => { "xml" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transactional" do
      transactional = Transactional.create! valid_attributes
      expect {
        delete :destroy, {:id => transactional.to_param}, valid_session
      }.to change(Transactional, :count).by(-1)
    end

    it "redirects to the transactionals list" do
      transactional = Transactional.create! valid_attributes
      delete :destroy, {:id => transactional.to_param}, valid_session
      response.should redirect_to(transactionals_url)
    end
  end

end
