require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe XslModulesController do

  # This should return the minimal set of attributes required to create a valid
  # XslModule. As you add validations to XslModule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "xsl" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # XslModulesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all xsl_modules as @xsl_modules" do
      xsl_module = XslModule.create! valid_attributes
      get :index, {}, valid_session
      assigns(:xsl_modules).should eq([xsl_module])
    end
  end

  describe "GET show" do
    it "assigns the requested xsl_module as @xsl_module" do
      xsl_module = XslModule.create! valid_attributes
      get :show, {:id => xsl_module.to_param}, valid_session
      assigns(:xsl_module).should eq(xsl_module)
    end
  end

  describe "GET new" do
    it "assigns a new xsl_module as @xsl_module" do
      get :new, {}, valid_session
      assigns(:xsl_module).should be_a_new(XslModule)
    end
  end

  describe "GET edit" do
    it "assigns the requested xsl_module as @xsl_module" do
      xsl_module = XslModule.create! valid_attributes
      get :edit, {:id => xsl_module.to_param}, valid_session
      assigns(:xsl_module).should eq(xsl_module)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new XslModule" do
        expect {
          post :create, {:xsl_module => valid_attributes}, valid_session
        }.to change(XslModule, :count).by(1)
      end

      it "assigns a newly created xsl_module as @xsl_module" do
        post :create, {:xsl_module => valid_attributes}, valid_session
        assigns(:xsl_module).should be_a(XslModule)
        assigns(:xsl_module).should be_persisted
      end

      it "redirects to the created xsl_module" do
        post :create, {:xsl_module => valid_attributes}, valid_session
        response.should redirect_to(XslModule.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved xsl_module as @xsl_module" do
        # Trigger the behavior that occurs when invalid params are submitted
        XslModule.any_instance.stub(:save).and_return(false)
        post :create, {:xsl_module => { "xsl" => "invalid value" }}, valid_session
        assigns(:xsl_module).should be_a_new(XslModule)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        XslModule.any_instance.stub(:save).and_return(false)
        post :create, {:xsl_module => { "xsl" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested xsl_module" do
        xsl_module = XslModule.create! valid_attributes
        # Assuming there are no other xsl_modules in the database, this
        # specifies that the XslModule created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        XslModule.any_instance.should_receive(:update_attributes).with({ "xsl" => "MyText" })
        put :update, {:id => xsl_module.to_param, :xsl_module => { "xsl" => "MyText" }}, valid_session
      end

      it "assigns the requested xsl_module as @xsl_module" do
        xsl_module = XslModule.create! valid_attributes
        put :update, {:id => xsl_module.to_param, :xsl_module => valid_attributes}, valid_session
        assigns(:xsl_module).should eq(xsl_module)
      end

      it "redirects to the xsl_module" do
        xsl_module = XslModule.create! valid_attributes
        put :update, {:id => xsl_module.to_param, :xsl_module => valid_attributes}, valid_session
        response.should redirect_to(xsl_module)
      end
    end

    describe "with invalid params" do
      it "assigns the xsl_module as @xsl_module" do
        xsl_module = XslModule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        XslModule.any_instance.stub(:save).and_return(false)
        put :update, {:id => xsl_module.to_param, :xsl_module => { "xsl" => "invalid value" }}, valid_session
        assigns(:xsl_module).should eq(xsl_module)
      end

      it "re-renders the 'edit' template" do
        xsl_module = XslModule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        XslModule.any_instance.stub(:save).and_return(false)
        put :update, {:id => xsl_module.to_param, :xsl_module => { "xsl" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested xsl_module" do
      xsl_module = XslModule.create! valid_attributes
      expect {
        delete :destroy, {:id => xsl_module.to_param}, valid_session
      }.to change(XslModule, :count).by(-1)
    end

    it "redirects to the xsl_modules list" do
      xsl_module = XslModule.create! valid_attributes
      delete :destroy, {:id => xsl_module.to_param}, valid_session
      response.should redirect_to(xsl_modules_url)
    end
  end

end
